services:
  app:
    container_name: qa-tools-app
    image: qa-tools-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
