[tool.pytest.ini_options]
addopts = "--cov=app --cov-report=term --cov-report=term-missing"

[tool.mypy]
files = ["app"]
exclude = "^app/static/"
ignore_missing_imports = true
strict = true

[tool.coverage.run]
omit = [
    "*/tests/*",
    "*/__init__.py",
    "*/config.py"
]